<x-layouts.app>
    <div class="m-4 sm:m-8">
        <p>
            <a href="/" class="text-emerald-500 hover:text-emerald-600 active:text-emerald-700 dark:text-emerald-300 hover:dark:text-emerald-200 active:dark:text-emerald-100 cursor-pointer hover:underline">&larr; Back to Plant Sale Entry</a>
        </p>
        <div class="space-y-2 mb-4 sm:mb-6">
            <h1 class="font-bold text-4xl sm:text-5xl">Terms of Service</h1>
            <p>Welcome! This website is operated by T6 Software LLC on behalf of Friends School of Minnesota.</p>
            <div class="bg-yellow-800 text-yellow-100 px-3 py-2 rounded-lg">
                The Terms of Service stated here only concerns the terms under which you may use <code>entry.friendsschoolplantsale.com</code>. Other systems and websites used by Friends School of Minnesota or the Friends School Plant Sale are governed by separate terms of service.
            </div>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">In a nutshell</h2>
            <ul class="list-disc pl-8 space-y-1">
                <li>This website is provided as a courtesy service to assist you with your shopping experience at the Friends School Plant Sale. It's provided to you as-is with no express or implied warranty, and may include software defects.</li>
                <li>You can choose to provide us with your phone number and subscribe to certain notifications about the Plant Sale. If you subscribe, we will make reasonable efforts to notify you about the topic(s) you select. While we do not charge for this service, messaging and data rates from your carrier may apply. You can unsubscribe from our messages at any time.</li>
                <li>You represent that you are at least 13 years old (and, if you're between the ages of 13 and 18, you are using this website with the permission of your parent or guardian). If you subscribe to text messages, you also represent that you are the current subscriber for the phone number you provide us, or you have permission from the subscriber to add them. (In other words, you can't sign up random phone numbers to get text messages from us.)</li>
                <li>Unless you have written authorization to do so, you can't use automated tools to interact with the website, and we reserve the right to take any reasonable defensive measures to enforce this rule. This also means you cannot intentionally interrupt the service on this website to others.</li>
                <li>Any estimated entry times that we provide on this website are esimates and not guarantees. Plant Sale event staff will make the final determination on when each group is admitted based on actual conditions inside the sale area.</li>
                <li>Finally, the software on this website is copyrighted and the data used by this website (such as entry group information) is generally considered proprietary and property of Friends School of Minnesota. Any information that is published is intended for your personal use "in the moment". You cannot run analysis on our data without our permission.</li>
            </ul>
            <p>If you do not agree with these terms of service, <strong>you must exit this website immediately.</strong> Further usage of this website, including subscribing to text messages, constitutes acceptance of these terms.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Changes to these terms</h2>
            <p>We may revise and update these Terms of Service from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the website thereafter. However, any changes to the dispute resolution provisions set out in the state of Minnesota will not apply to any disputes for which the parties have actual notice or before the date the change is posted on the website.</p>
            <p>Your continued use of the website following the posting of revised Terms of Service means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Access and security requirements</h2>
            <p>We reserve the right to withdraw or amend this website, and any service or material we provide on the website, in our sole discretion without notice. We will not be liable if for any reason all or any part of the website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the website, or the entire website, to users, including registered users.</p>
            <p>You are responsible for making all necessary arrangements for you to access and use the website.</p>
            <p>To access the website or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of the website that all the information you provide on the website is correct, current, and complete. You agree that all information you provide to register with this website or otherwise, including, but not limited to, through the use of any interactive features on the website, is governed by <a href="{{ route('privacy') }}" class="text-emerald-200 hover:text-emerald-100 cursor-pointer hover:undelrine">our Privacy Policy</a>, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Intellectual property rights</h2>
            <p>This website and its entire contents, including all information, software, text, and data displayed on the website, are owned by Friends School of Minnesota or a licensor under agreement with Friends School of Minnesota. All such material is protected by laws and treaties of the United States, the State of Minnesota, and other countries concerning copyright and trademark.</p>
            <p>You are permitted to use the website for personal and non-commercial use only. You are not permitted to reproduce or reverse-engineer the website, its underlying software or data, or its features without our permission.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Prohibited uses</h2>
            <p>You may use this website only for lawful purposes and those that are consistent with these Temrs of Service. You may not use this website:</p>
            <ul class="list-disc pl-8 space-y-1">
                <li>In any way that violates a local, state, federal, or international law, regulation, ordinance, or treaty</li>
                <li>To transmit, or cause us to transmit on your behalf, advertising or promotional materials unaffiliated with the Friends School Plant Sale</li>
                <li>To cause anyone other than you to receive text message alerts from us</li>
                <li>To impersonate or attempt to impersonate the Friends School Plant Sale, its staff, another user, or any other person or entity</li>
                <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the website, or which, as determined by us, may harm Friends School of Minnesota, T6 Software LLC, or users of the website, or expose them to liability</li>
                <li>In any manner that could disable, overburdern, damage, or impair the site or interfere with any other party's permitted use of the website, including their ability to engage in real-time activiies</li>
                <li>Via any robot, spider, or any other automated device, process, or means to access the website or its data for any purpose, including via "screen scraping" tools and AI agents</li>
            </ul>
            <p>Additionally, you must not:</p>
            <ul class="list-disc pl-8 space-y-1">
                <li>Launch any type of denial of service attack against the website</li>
                <li>Manually copy data from the website without our permission</li>
                <li>Attempt to reverse-engineer the software powering the website without our permission</li>
                <li>Attempt to access restricted parts of the website without authorization and a need to know</li>
                <li>Attempt to circumvent any restrictions we place on your access as a security measure or as a consequence of violating these Terms of Service</li>
            </ul>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Reliance on information posted or sent to you via text messages</h2>
            <p>The information presented on or through the website, or through any text messages we send you as a result of you subscribing through this website, is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the website, or by anyone who may be informed of any of its contents.</p>
            <p><strong>This is especially important with group distribution and admission time information.</strong> Unless otherwise noted, all group admission times are <strong>ESTIMATES AND SUBJECT TO CHANGE WITHOUT NOTICE</strong>. Plant Sale event coordinators adjust group admission times frequently based on safety considerations, shopping cart availability, checkout line wait times, and other factors both within and beyond our control, and there may be a delay between when our estimate of an admission time changes and when that new time is posted to the website.</p>
            <div class="bg-yellow-800 text-yellow-100 px-3 py-2 rounded-lg">
                In order to have access to the best selection of available plants for purchase, you are responsible for physically being present at the Grandstand West Apron when your group number is officially admitted. Groups are admitted in numerical order. If you leave the area and come back after your group is admitted, you will still be able to shop, but the availability of plants inside the sale will be different compared with what it would have been had you entered on time with your group. Leaving the Plant Sale campus with the intention of returning when your group is admitted is <strong>at your own risk</strong>.
            </div>
            <p>If there is a conflict between information provided on the website and information provided on signage at the Plant Sale, <strong>information on signage at the Plant Sale takes priority.</strong></p>
            <p>Though we and your carrier will make all reasonable efforts to deliver any requested text message notifications to you as quickly as they become available, we or your carrier may delay or block a message from being delivered to you from time to time even though you have requested a message via the website.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Geographic restrictions</h2>
            <p>The owner of the website is based in the State of Minnesota in the United States. We provide this website for use only by persons located in the United States. We make no claims that the website or any of its content is accessible or appropriate outside of the United States. Access to the website may not be legal by certain persons or in certain countries. If you access the website from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Disclaimer of warranties</h2>
            <p>You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the website will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT.</p>
            <p>YOUR USE OF THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER FRIENDS SCHOOL OF MINNESOTA NOR ANY PERSON ASSOCIATED WITH FRIENDS SCHOOL OF MINNESOTA MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE WEBSITE. WITHOUT LIMITING THE FOREGOING, NEITHER FRIENDS SCHOOL OF MINNESOTA NOR ANYONE ASSOCIATED WITH FRIENDS SCHOOL OF MINNESOTA REPRESENTS OR WARRANTS THAT THE WEBSITE, ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</p>
            <p>TO THE FULLEST EXTENT PROVIDED BY LAW, FRIENDS  HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</p>
            <p>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Limitation of liability</h2>
            <p>TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL FRIENDS SCHOOL OF MINNESOTA, ITS AFFILIATES, OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEBSITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE WEBSITE OR SUCH OTHER WEBSITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE.</p>
            <p>The limitation of liability set out above does not apply to liability resulting from our gross negligence or willful misconduct.</p>
            <p>THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Indemnification</h2>
            <p>You agree to defend, indemnify, and hold harmless Friends School of Minnesota, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms of Service or your use of the website, including, but not limited to, your User Contributions, any use of the website's content, services, and products other than as expressly authorized in these Terms of Service, or your use of any information obtained from the website.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Governing law and jurisdiction</h2>
            <p>All matters relating to the website and these Terms of Service, and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of Minnesota without giving effect to any choice or conflict of law provision or rule (whether of the State of Minnesota or any other jurisdiction).</p>
            <p>Any legal suit, action, or proceeding arising out of, or related to, these Terms of Service or the website shall be instituted exclusively in the federal courts of the United States or the courts of the State of Minnesota, in each case located in the City of Saint Paul and County of Ramsey, although we retain the right to bring any suit, action, or proceeding against you for breach of these Terms of Service in your country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Arbitration</h2>
            <p>At our sole discretion, we may require you to submit any disputes arising from these Terms of Service or use of the website, including disputes arising from or concerning their interpretation, violation, invalidity, non-performance, or termination, to final and binding arbitration under the Rules of Arbitration of the American Arbitration Association applying Delaware law.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Limitation on time to file claims</h2>
            <p>ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR THE WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Waiver and severability</h2>
            <p>No waiver by Friends School of Minnesota of any term or condition set out in these Terms of Service shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Friends School of Minnesota to assert a right or provision under these Terms of Service shall not constitute a waiver of such right or provision.</p>
            <p>If any provision of these Terms of Service is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Service will continue in full force and effect.</p>
            <h2 class="font-semibold text-2xl sm:text-3xl pt-4">Entire agreement</h2>
            <p>The Terms of Service and our Privacy Policy constitute the sole and entire agreement between you and Friends School of Minnesota regarding the website and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the website.</p>
            <p>
                <a href="/" class="text-emerald-200 hover:text-emerald-100 cursor-pointer hover:undelrine">&larr; Back to Plant Sale Entry</a>
            </p>
        </div>
    </div>
</x-layouts.app>
